### ISSUE TITLE
Missing style quotes: auto; ?

### ISSUE THREAD

**Issue by kgnfth** [beyondcode/windy-community#10]
What is that, its on every website when i use windy 😂

![image](https://user-images.githubusercontent.com/73314940/107422296-2260f280-6b1b-11eb-8a68-9fa2dcd5b2e3.png)

**Comment by sschlein** [comment]
🙈
<img width="1016" alt="CleanShot 2021-02-09 at 21 15 51@2x" src="https://user-images.githubusercontent.com/2911113/107422933-01e56800-6b1c-11eb-9adb-ce86b9520566.png">

**Comment by kgnfth** [comment]
@sschlein i use windows built-in screen copier PRT SC + CTRL V
I don`t care about cropping if that's what you mean by the screen shot reply 🤣

**Comment by kgnfth** [comment]
?

**Comment by sschlein** [comment]
Ok that was to meta. I get this too and I'm working on the extension - no idea why I haven't put attention to this until now.

We are going to look into it.

**Comment by sschlein** [comment]
This has already been solved in 1.1.0
