### ISSUE TITLE
Safari Support

### ISSUE THREAD

**Issue by mikebronner** [beyondcode/windy-community#13]
I emailed a while back discussing the options for Safari support, and it was indicated back then that it was something being worked on. I was delighted to hear that, but haven't seen or heard anything since.

I would love to see a Safari extension published for Windy, as Safari is the only browser I currently use.

Thanks! :)

**Comment by mechelon** [comment]
This seems to be an edge case - we could not reproduce this. Please reopen the issue if the problem still occurs.

**Comment by mikebronner** [comment]
@mechelon I'm not sure how this is an edge case that you could not reproduce?

**Comment by mechelon** [comment]
@mikebronner Whoops, wrong answer for this issue. 😅  There you go –

This is currently not on our short-term roadmap, so I will close this for now. We might come back to this later.

**Comment by mikebronner** [comment]
Thanks for the update. Was really hoping for this. Hopefully it will be possible eventually.
