### ISSUE TITLE
Copying block of nested html with tailwind class

### ISSUE THREAD

**Issue by ravinsharma7** [beyondcode/windy-community#16]
windy is useful if just want to get the closes approximate tailwind class for a single html element. 

For more useful real world usage, being able to copy the block of nested html with the tailwind classes seem to be closer to real usage.

Another tool https://getcssscan.com/ provides this feature. windy would be extremely useful and valuable if it can do this. At the moment the use case is quite simple.

**Comment by mpociot** [comment]
I don't really understand the reported issue. Copying a block of nested HTML with Tailwind classes is the default behavior of Windy
