### ISSUE TITLE
[Feature Request]: Safari / MacOSX

### ISSUE THREAD

**Issue by docgonzo2015** [beyondcode/windy-community#21]
### Feature Description

All articles about windy said that the extension will be released in January 2021. I do not find it. Were there any problems?

**Comment by mechelon** [comment]
We don't launch the Safari plugin anymore because it's quite a hassle and only 1/1000 customers needs this. All others are happy with Chrome and Firefox and so we decided to focus on them – this is why we removed this from the website.
