### ISSUE TITLE
Ability to add prefix

### ISSUE THREAD

**Issue by Corys8646** [beyondcode/windy-community#3]
I'm typically adding tailwind to an already established site, which requires setting a prefix for tailwind. Would be awesome if I could set a prefix for windy generated code. Great job on the plugin.

**Comment by sschlein** [comment]
This could also be solved with this:

https://github.com/beyondcode/windy-community/issues/4

**Comment by sschlein** [comment]
This will launch with version 1.1. that we have submitted to the chrome web store today. It will be available once google finished the review shortly.
