### ISSUE TITLE
When Does WINDY supports Tailwind CSS 3 ? [Feature Request]: 

### ISSUE THREAD

**Issue by james-wong123** [beyondcode/windy-community#30]
### Feature Description

Really been waiting for it. Hopefully it is coming before March !

**Comment by stefanwuthrich** [comment]
good question. Waiting for it long time now.
Considering that there are other similar products (including free ones).... it would be great to get this update soon
Tks

**Comment by james-wong123** [comment]
That's what they reply to me, 

```
Hi James,

we are working on the update right now and plan to release it at the end of this month or the week after.

The new Tailwind version requires a new algorithm written from scratch to support JIT engine features, etc. This is why it takes so long.

Best regards,
Sebastian
```

**Comment by sschlein** [comment]
It should be available today or tomorrow. We've uploaded the extension to the extension stores and are waiting for their approval. 

:)

**Comment by james-wong123** [comment]
@sschlein Noted, Thx !

**Comment by sschlein** [comment]
@stefanwuthrich Can you point me to the alternatives? I'd like to learn what we can improve. 

We're also giving more insights into the near roadmap for Windy in todays newsletter at [beyondco.de](https://beyondco.de/newsletter)

**Comment by stefanwuthrich** [comment]
> @stefanwuthrich Can you point me to the alternatives? I'd like to learn what we can improve.
> 
> We're also giving more insights into the near roadmap for Windy in todays newsletter at [beyondco.de](https://beyondco.de/newsletter)

Tks for updating :-)

Paid one : https://www.inspectflow.io/
And very basic, but free one: https://chrome.google.com/webstore/detail/css-to-tailwind/jlmlldiahhaejpjnonbddoniicdemakl

**Comment by james-wong123** [comment]
> Paid one : https://www.inspectflow.io/
> And very basic, but free one: https://chrome.google.com/webstore/detail/css-to-tailwind/jlmlldiahhaejpjnonbddoniicdemakl

Thx for your information also, 
An interesting alternative to DevTool, in fact, I think it is better than dev tools at a similar price.

**Comment by sschlein** [comment]
I just bought Inspectflow and tried the free extension:

The free extension only allows you to copy the Tailwind Classes of the element and doesn't look for child and parent elements, so it might be helpful but is far from a competitor. The CSS mode (that we'll release soon too) is interesting but doesn't help you when building a tailwind site.

Inspectflow doesn't seem to work for me if the Stylesheet is purged or using JIT mode. That feels worthless to me for Tailwind 3 because you can add classes that aren't present in the stylesheet and don't see something happen on the site. Our DevTools even let you use arbitrary values that arent available in the stylesheet at all. I Like the way how to add classes in the popover instead of a devtools panel, this might be an idea we could add to our devtools too.

😉

**Comment by stefanwuthrich** [comment]
> I just bought Inspectflow and tried the free extension:
> 
> The free extension only allows you to copy the Tailwind Classes of the element and doesn't look for child and parent elements, so it might be helpful but is far from a competitor. The CSS mode (that we'll release soon too) is interesting but doesn't help you when building a tailwind site.
> 
> Inspectflow doesn't seem to work for me if the Stylesheet is purged or using JIT mode. That feels worthless to me for Tailwind 3 because you can add classes that aren't present in the stylesheet and don't see something happen on the site. Our DevTools even let you use arbitrary values that arent available in the stylesheet at all. I Like the way how to add classes in the popover instead of a devtools panel, this might be an idea we could add to our devtools too.
> 
> wink

I fully agree that your extension is the best. That's the reason I bought it and want (and can) to continue with TW 3 support :-)

**Comment by sschlein** [comment]
The DevTools even work on non-Tailwind sites. Not that it would be useful for anyone, but they do 😂

![CleanShot 2022-03-09 at 09 28 23@2x](https://user-images.githubusercontent.com/2911113/157402329-79b6fe33-85c6-44ef-82d8-42c61037327c.png)
