### ISSUE TITLE
Is Windy 1.0.6 really working? 🤔

### ISSUE THREAD

**Issue by mathieutu** [beyondcode/windy-community#9]
Hi, an issue just to let you know, that I'm trying to use windy on [a website](https://www.service-public.fr/) which fights back and doesn't want to let me copy its style!

I've done several tries on several blocks on Firefox an Chrome, but didn't succeed to make Windy working on it.
Also the tests were very long to copy, and I had to tell Firefox to not kill it and wait many times.

I don't know if this is a pretty standard limit of Windy and I will not be able to get something better from it, or if you have some tips for theses cases.

Some examples:
![Screenshot 2020-12-14 at 22 26 14](https://user-images.githubusercontent.com/11351322/102137800-aff5ce00-3e5b-11eb-9b06-ef15a68478b2.png)

![Screenshot 2020-12-14 at 22 26 26](https://user-images.githubusercontent.com/11351322/102137937-e7647a80-3e5b-11eb-841d-931ca15f111d.png)

![Screenshot 2020-12-14 at 22 32 41](https://user-images.githubusercontent.com/11351322/102138380-8b4e2600-3e5c-11eb-8587-2baf71bdb4f8.png)

![Screenshot 2020-12-14 at 22 32 21](https://user-images.githubusercontent.com/11351322/102138432-9dc85f80-3e5c-11eb-88e3-8a463d0c30c4.png)

![Screenshot 2020-12-14 at 22 31 51](https://user-images.githubusercontent.com/11351322/102138466-aae54e80-3e5c-11eb-8983-a2c6f4543c1a.png)

Thanks!
Mathieu.

**Comment by mathieutu** [comment]
Actually, I've tried on the github header of this issue just for fun, and it's a bit better, but not much, so I think this is just Windy limitations.. 🤷‍♂️

![image](https://user-images.githubusercontent.com/11351322/102139114-ab321980-3e5d-11eb-9234-fe3e6d8cf749.png)

![Screenshot 2020-12-14 at 22 43 20](https://user-images.githubusercontent.com/11351322/102139298-f3e9d280-3e5d-11eb-859a-51c47d04f44f.png)

**Comment by mathieutu** [comment]
And with your own website, but now I'm wondering if there can be something wrong with the last version, as it's not working at all on it 😅

We can see it adds a gray border, and I've no idea where it comes from, by reading your classes
![Screenshot 2020-12-14 at 22 54 57](https://user-images.githubusercontent.com/11351322/102140370-6c9d5e80-3e5f-11eb-9e5e-fde29f97160f.png)

The result: https://play.tailwindcss.com/JTc4IjaG8J

![Screenshot 2020-12-14 at 22 58 16](https://user-images.githubusercontent.com/11351322/102140655-e03f6b80-3e5f-11eb-8495-a138adc9a2cb.png)

**Comment by sschlein** [comment]
Hey, there is an issue with Windy on our own website as this conflicts with the demo code.  

Anyway, we have submitted 1.1 to the Chrome Web Store and this should fix your issues once it is live. We are also launching an new website for Windy :)

**Comment by mathieutu** [comment]
Ok thanks. I'll let you know if I still see the problems.
